### ISSUE TITLE
F-14: MP Backseating doesn't seem to be working

### ISSUE THREAD

**Issue by Zaretto** [Zaretto/fg-aircraft#126]
no power to anything, could be a Nasal error

![image](https://user-images.githubusercontent.com/2045654/106441598-8aa83800-647a-11eb-8d39-6f5bc1583367.png)

![image](https://user-images.githubusercontent.com/2045654/106441558-7b28ef00-647a-11eb-91d5-d7886c8c64c3.png)

from: SammySkycrafts | EAGLE | 48thFW:

**Comment by NikolaiVChr** [comment]
This should be fixed with PR #157

**Comment by Megaf** [comment]
> This should be fixed with PR #157

Indeed. This issue can be closed.

**Comment by geneb** [comment]
...there's no flight controls in the back seat of an F-14.

**Comment by SammySkycrafts** [comment]
> ...there's no flight controls in the back seat of an F-14.

There are controls, just not ones that can fly the aircraft. At no point in the issue did anyone mention flight controls. The important ones have now been implemented using a new system when the radar was reworked.

**Comment by geneb** [comment]
The screen shot at the top appears to be showing the rear cockpit - there's no center window framing visible, so I'd assumed the screen shot was taken from the rear.

**Comment by SammySkycrafts** [comment]
> The screen shot at the top appears to be showing the rear cockpit - there's no center window framing visible, so I'd assumed the screen shot was taken from the rear.

Correct, this is the back seat, and correct, there are no flight controls there, so im not sure what you was referring to?

**Comment by geneb** [comment]
The figure appears to be holding a stick - maybe it's just the figure that's incorrect. :)

**Comment by Megaf** [comment]
> The figure appears to be holding a stick - maybe it's just the figure that's incorrect. :)

That's just a generic pilot 3D model. It is wrong indeed.
The F-14 never had flight controls on the back seat.

Back seat radar/weapon controls are working now. Apart from A/A missile launch button on the left side.

**Comment by geneb** [comment]
On Thu, 2 Feb 2023, Megaf wrote:

> Back seat radar/weapon controls are working now. Apart from A/A missile launch button on the left side.
>

Glad to hear it!

g.

-- 
Proud owner of F-15C 80-0007
http://www.f15sim.com - The only one of its kind.
http://www.diy-cockpits.org/coll - Go Collimated or Go Home.
Some people collect things for a hobby.  Geeks collect hobbies.

ScarletDME - The red hot Data Management Environment
A Multi-Value database for the masses, not the classes.
http://scarlet.deltasoft.com - Get it _today_!
