### ISSUE TITLE
F-14: Wobbling knobs and unaligned switches.

### ISSUE THREAD

**Issue by Megaf** [Zaretto/fg-aircraft#128]
The lights knobs on the right side wobbles when you spin them, also, there are a few switches around the cockpit that are out of place, like the weapons switches on the left side of the radio operator

**Comment by Megaf** [comment]
Fixed on develop branch.

**Comment by Zaretto** [comment]
Closing as accepted as fixed

**Comment by Megaf** [comment]
The following items in the RIO area are still misaligned.
![RIO-ECM](https://user-images.githubusercontent.com/6201512/118358375-66c6b900-b576-11eb-916e-e88c41cf4990.png)
![RIO-Radar_Knobs](https://user-images.githubusercontent.com/6201512/118358379-6cbc9a00-b576-11eb-8f36-b4ed74eb80bf.png)
![RIO-Radio](https://user-images.githubusercontent.com/6201512/118358380-6e865d80-b576-11eb-9227-8f7550b685ba.png)
