### ISSUE TITLE
What's the max value of p-rad of F15?

### ISSUE THREAD

**Issue by theorynice** [Zaretto/fg-aircraft#131]
Hi, Zaretto，thanks very much for your great work. May I ask what's the max value of p-rad of F15?  Can F15 make an Immelmann turn or kulbit maneuvering in FlightGear?

**Comment by Zaretto** [comment]
All I can tell you is that my F-15 will roll at ~800deg/sec (14 rad/sec) with roll ratio emerg and about 180deg/sec (~3rad/sec) with roll ratio normal.

Immelman turns yes. Kulbit no.
