### ISSUE TITLE
F-14: HUD/Radar misidentifying targets

### ISSUE THREAD

**Issue by Megaf** [Zaretto/fg-aircraft#135]
In this case, an F-16 was seeing as a 777.
![image](https://user-images.githubusercontent.com/6201512/117587112-344f3300-b114-11eb-93a9-f44c9ad6ecd4.png)

It doesn't happen very often, but it does. Not sure how to debug this.

**Comment by Megaf** [comment]
I've been doing some more investigation, in the screenshot below we see an object in the radar. That was an online pilot.
The thing is, that pilot had disconnected already, yet, in the radar it stays at the relative heading it was when they disconnected.
However, the relative distance to the F-14 remains static, no matter how long I fly, the target will never get closer.
![fgfs-20210525113042](https://user-images.githubusercontent.com/6201512/119491229-984d3a80-bd55-11eb-9331-226c6e666066.png)

**Comment by NikolaiVChr** [comment]
Develop branch? Radar mode?

**Comment by regier** [comment]
This was before the radar rewrite. It was the development branch.
The issue can be closed now.

**Comment by Megaf** [comment]
> Develop branch? Radar mode?

Development branch indeed. I'm not sure about the radar mode.
Haven't noticed the issue lately, I think it's fixed now. Will close the issue.

**Comment by NikolaiVChr** [comment]
I think a nasal error was the cause of this. Hence why the radar picture remained unchanged.
The radar would have stopped updating the properties that drives the display.
If it happens again, I would post a log file.
