### ISSUE TITLE
F-14: Tyre smokes cause significant FPS drop on touchdown.

### ISSUE THREAD

**Issue by Megaf** [Zaretto/fg-aircraft#137]
If you are in external view. When rolling the tyres cause a lot of smoke, that have a significant impact on performance.

I propose two options to improve this.
1. Change the "type" of smoke particle used, the smoke from smoke pods/air show have almost no impact on performance and could be used instead, they are very similar.
2. I am not sure if it's realistic to always have smoke coming from the tyres when rolling, perhaps making it show up only of a second or two on touchdown would be better?

Options 1 and 2 could very well work together.

**Comment by Zaretto** [comment]
The F-14 uses the standard FlightGear tyre smoke system; which will simulate both touchdown smoke and spray (when raining)

rain is controlled by environment/metar/rain-norm

There shouldn't always be smoke when rolling unless it is a wet runway.

**Comment by Megaf** [comment]
I will try again with a manual METAR for dry conditions and report back.

**Comment by Megaf** [comment]
METAR for the test.
![image](https://user-images.githubusercontent.com/6201512/118193994-8956b600-b440-11eb-9919-20cc674d6897.png)
![image](https://user-images.githubusercontent.com/6201512/118193862-51e80980-b440-11eb-86e6-e89f0df22473.png)
"Smoke" starts at 60 kias
![fgfs-20210513220621](https://user-images.githubusercontent.com/6201512/118193892-5f9d8f00-b440-11eb-91f9-c60a8ae527b5.png)
And it stops at 120
![fgfs-20210513220629](https://user-images.githubusercontent.com/6201512/118193930-72b05f00-b440-11eb-9a1b-f85b74d35b61.png)

**Comment by Zaretto** [comment]
can you put property /environment/metar/rain-norm onto the screen so we can see if that is what is causing the smoke.

**Comment by Megaf** [comment]
With `rain-norm=0` The sprays shows up as reported above, starts at around 70 kts and stops at around 120.
![fgfs-20210514124925](https://user-images.githubusercontent.com/6201512/118273113-703f1b00-b4bb-11eb-980f-521c3f717a4f.png)
With `rain-norm=1` The sprays starts as soon as the aircraft starts moving and stops once the aircraft leaves the ground.

**Comment by Zaretto** [comment]
I've now investigated this and the tyresmoke system in the core Nasal needs some work; namely.

* Touchdown tyre smoke should only happen just after touchdown
* Spray should be based upon standing water and the drag of the wheel through the water; which is a curve; not a simple function. Data was found in NASA TN D-3515 "Figure 31.- Variation of drag parameter with ground speed in water for dual tandem-wheels with and without spray-drag alleviators. "

Revised system seems to work better.

Prior to changing the core I've wired this into the F-14 for testing.

https://i.imgur.com/FkwgoYV.gifv

**Comment by Zaretto** [comment]
I'm also intending to apply the core fix to 2020 LTS

**Comment by Megaf** [comment]
Commit 637e63e57aeacd9c5273d5dd333b587babed5c69 fixed most of the issues.

### Water Spray
- Spray only triggered it rainy conditions. :+1: 
- Spray doesn't have any noticeable performance impact. :+1: 

### Tyre Smoke
- Tyre Smoke is only triggered for a brief moment on touchdown. :+1: 
- Tyre Smoke still cause a significant FPS drop and even a brief "freeze" upon touchdown. :-1: 

Overall, I am happy, but I think the tyre smoke could be improved. I edited the issue title to reflect the current status.

**Comment by Zaretto** [comment]
Fixes pushed to develop for smoke/spray in air.

**Comment by Zaretto** [comment]
I'm closing this because the performance issues cannot be fixed whilst retaining something that looks right.
