### ISSUE TITLE
Unable to Clone Repository, Extract downloaded .Zip file.

### ISSUE THREAD

**Issue by AnirudhP22** [Zaretto/fg-aircraft#144]
Hi Richard,

I really like the amount of work that you have done for F-14 in FlightGear.
Previously I was using old version of FG and F-14b was working well, but now I am using FlightGear v 2020.3.3 & aircraft is not loading.
So I trayed to use F-14 model V1.3 (FG 3.6+) from link = http://www.zaretto.com/sites/zaretto.com/files/F-14-13-fg36-2015-11-30.zip
Looks like its not compatible with FG v 2020.3.3 so I also tried to Clone Develop Repository (https://github.com/Zaretto/fg-aircraft/tree/develop) but unable to Clone it, I am getting error.
So i also tried to Download .Zip from Github.
I managed to download 378MB file, but while extracting .Zip file I am getting error as seen in attached screenshot below.
![Error](https://user-images.githubusercontent.com/72618308/119372905-7ad88c00-bcd5-11eb-8c4c-8d36a20daf32.jpg)

**Comment by Zaretto** [comment]
Thanks for the positive feedback.

The V1.3 (FG 3.6+) on zareto.com is very old and probably should be removed from my site.

It is recommended to use the FlightGear launcher to install the F-14 (and F-15). 

![image](https://user-images.githubusercontent.com/2045654/119376985-dd715e00-bcbc-11eb-92d1-5e04e299ae44.png)

Currently the develop branch is working fine with 2020.3 - however the best way to get this is to clone it using git; downloading the zipfile isn't ideal as it will be large.

I will be releasing updated versions of the F-14 and F-15 within the next month or so; and these will be available in the 2020.3 aircraft menu.

**Comment by AnirudhP22** [comment]
Using the FlightGear launcher I managed to download updated F-14 for FG v 2020.3.3 and its working.
Thank you.

I wanted to clone repository from Develop Branch of F-14b from Github, but I am getting clone button only for fg-aircraft i.e. [https://github.com/Zaretto/fg-aircraft/tree/develop](url) marked in below screenshot.
![Develop fg-aircraft](https://user-images.githubusercontent.com/72618308/119774090-459f8a00-bedf-11eb-8d2b-2872aa7b6c05.jpg)

Main fg-aircrat is more then 1GB in size, I want to only clone F-14b or F-15 without "Development-Items" folder.
Inside F-14b [https://github.com/Zaretto/fg-aircraft/tree/develop/aircraft/f-14b](url) repository I cant see clone button, pleas see attached screenshot.
![Develop f-14b](https://user-images.githubusercontent.com/72618308/119774124-53eda600-bedf-11eb-8030-b8a00bf6e646.jpg)

**Comment by Zaretto** [comment]
github doesn't support downloading a subdirectory; so the only way to do this would be to use git command line.

I'm closing this issue because it isn't really F-14 or F-15 related.

**Comment by AnirudhP22** [comment]
Ok, Thankyou.

Is it possible to clone subdirectory using GitHub Desktop?

**Comment by Megaf** [comment]
Unfortunately it isn't, that is not what Git is for nor how it works.
Git is for project management, so you clone the whole repo and work on it.

I would suggest you simply use the Aircraft available in the FGAddon Hangar.

**Comment by Zaretto** [comment]
@AnirudhP22 also worth noting that once you've cloned the repository getting the latest version will usually very much smaller downloads as git will only download the changes.
