### ISSUE TITLE
What's the relationship between  autoflight.xml and autoflight-rules.xml in F-15?

### ISSUE THREAD

**Issue by theorynice** [Zaretto/fg-aircraft#145]
Hi, Zaretto, thanks for your wonderful job. I recently want to develop an autopilot PID controller for F-15 based JSBSim, but failed. Thus, I want to refer to your work about autoflight. In autoflight-rules.xml, I see a comment saying no way to move to JSB. So, may I ask what's the relationship between  autoflight.xml and autoflight-rules.xml in F-15? May I move autoflight.xml to JSB to realize f15's autopilot?

**Comment by Zaretto** [comment]
autoflight-rules uses the FliightGear autopilot  https://wiki.flightgear.org/Autopilot_configuration_reference. If you look inside this file you will see that it is doing string comparisons (which are not supported by JSBSim). There are also elements that aren't supported in JSBSim.

e.g. 
`				<equals>
					<property>/autopilot/locks/heading</property>
					<value>dg-heading-hold</value>
				</equals>
`

autoflight,xml is already a JSBSim system that does most of the work - and it works with autoflight-rules

**Comment by theorynice** [comment]
I see, thanks for your help

**Comment by theorynice** [comment]
> autoflight,xml is already a JSBSim system that does most of the work

Excuse me, I have found autoflight-rules.xml was added into f15-common.xml, such as:
```
 <systems>
            <autopilot n="0">
                <path>Aircraft/F-15/Systems/autoflight-rules.xml</path>
            </autopilot>
        </systems>
```
But didn't find that autoflight.xml was added into autoflight-rules.xml neither 15-common.xml. So, I was confused about how autoflight.xml works with autoflight-rules.

**Comment by Zaretto** [comment]
autoflight is a JSBSim system included by the main JSBSim XML (f15a,xml)

see https://github.com/Zaretto/fg-aircraft/blob/master/aircraft/F-15/f15a.xml#L805

**Comment by theorynice** [comment]
> autoflight is a JSBSim system included by the main JSBSim XML (f15a,xml)
> 
> see https://github.com/Zaretto/fg-aircraft/blob/master/aircraft/F-15/f15a.xml#L805

Thank you very much. May I think the f15a.xml is the basic file for all variant f-15, and f15a.xml is introduced by `<aero>f15a</aero>` in f15-common.xml?

**Comment by Zaretto** [comment]
yes f15a.xml is the JSBSim model and it is referenced by the <aero> tags for a <flight-model> of type jsb 

ref: https://github.com/Zaretto/fg-aircraft/blob/master/aircraft/F-15/f15-common.xml#L108
