### ISSUE TITLE
Missing file f-14b-external-lighting.xml

### ISSUE THREAD

**Issue by colingeniet** [Zaretto/fg-aircraft#147]
For the F-14, on branch `develop`, file `f-14b/Models/f-14b-external-lighting.xml` (included from `f-14b/Models/f-14b.xml` at line 4881) is missing. It should have been added in commit https://github.com/Zaretto/fg-aircraft/commit/fdd1e046fc0089c2dc4170f67d9cfce847cec6e8.

**Comment by Megaf** [comment]
As far as I know, Richard is currently working on new lights. So, it's a known issue that he is working on.

**Comment by Zaretto** [comment]
Added missing files
