### ISSUE TITLE
Remove Phoenix pylons under body when load = FAD light

### ISSUE THREAD

**Issue by vanosten** [Zaretto/fg-aircraft#149]
When load = FAD light, then currently the 4 Phoenix pylons are still displayed (which they should not be) and therefore the 2 front AIM-7 are hidden apart from parts of the rockets' wings

**Comment by Zaretto** [comment]
All stores visibility over MP needs to be redone in the same way [as the F-15 using MP booleans for armaments](https://github.com/Zaretto/fg-aircraft/blob/develop/aircraft/F-15/Systems/armament-rules.xml)
