### ISSUE TITLE
Content on SIT page is smaller than it should be 

### ISSUE THREAD

**Issue by ZorkaA** [Zaretto/fg-aircraft#151]
Here's the display on the SIT page, seems like it should take up more than just one corner.

![fgfs-20220120115722](https://user-images.githubusercontent.com/68531996/150369805-fe546c34-fb66-4a10-855e-2046d03cda8f.png)

**Comment by Zaretto** [comment]
Thanks to Nikolai a much better SIT map will be available on this button soon.
![image](https://user-images.githubusercontent.com/2045654/150372123-e3c221bc-bdea-4325-83be-a65519a25afc.png)
