### ISSUE TITLE
F-14: lights on pilot right canopy

### ISSUE THREAD

**Issue by NikolaiVChr** [Zaretto/fg-aircraft#172]
These lights:
![image](https://user-images.githubusercontent.com/3764194/211711331-5e42bce9-e61f-4597-958b-b6f5ed6b9878.png)

Source: page 2-194 and 2-195 of NAVAIR 01-F14AAP-1.

The 3 middle ones could use some text and properties, it seems like the upper and lower is not used, or at least not described by the source:
```

SAM
AAA
AI

```
Right now its the 2 upper that is animated, it should be the 3 in the middle instead. Unless ofc. there is another version of the F-14 in which it is different.

Sadly this source does not indicate their colors.

**Comment by Zaretto** [comment]
![image](https://user-images.githubusercontent.com/2045654/212086323-8e14e844-f05e-4fb6-9f9c-7109caabf785.png)

possibly these colours (from HB F-14)
![image](https://user-images.githubusercontent.com/2045654/212087021-c8b11a44-94ba-46b9-8050-88f715fb7190.png)

**Comment by Zaretto** [comment]
redid left and right windshield lights

![image](https://user-images.githubusercontent.com/2045654/216241082-7b55db56-a4ef-413e-b49f-b5f1157d133f.png)

![image](https://user-images.githubusercontent.com/2045654/216241066-462c867c-f41a-40eb-8149-c20b374ab6d8.png)
