### ISSUE TITLE
M61A1 gun hit message

### ISSUE THREAD

**Issue by Developer0607** [Zaretto/fg-aircraft#175]
I noticed that in the F-15's submodels.xml,line124-155:
one gun shell submodel simulates 5 gun rounds.
So one hit should be reported as 5 hits.
In the release 1.12, the aircraft uses emesary damage code, when sending gun hit message, should the hit_counts be multiplied 5?

**Comment by NikolaiVChr** [comment]
Seems so, I will make a commit to fix both F-14 and F-15.

**Comment by Developer0607** [comment]
Thanks

**Comment by Developer0607** [comment]
And I will close this issue.
