### ISSUE TITLE
f-14b tacan heading

### ISSUE THREAD

**Issue by dirteat** [Zaretto/fg-aircraft#177]
Hi there,
I've been flying the latest snapshot of the devel version, and spotted (tested in multiplayer mode) that the tacan heading for carrier is not maintaining a constant, nor consistent, direction to the carrier when the plane turns.

The overall direction is roughly ok while flying straight, but making a loop clearly show the issue. The tacan heading rotates at a different angular speed than the CRS, which should not happen for an emitter far enough. It could just be a display problem with rotation on the navigation display. Also getting closer to the emitter (here the carrier), the difference between the real direction to the carrier and the one indicated by the tacan heading becomes evident.

Another rotation problem concerns the rotary button allowing to change the CRS, it is always spinning in one direction only, independently of the mouse input. Then, we can only decrease CRS whatever button we press on the mouse or whatever direction we spin the mouse's wheel.

The rest is fantastic, the manoeuvrability of that version is stunning! It feels also more powerful, a pure pleasure to fly!

Cheers,
Chris.

**Comment by Zaretto** [comment]
I will look into this. There have been other reports of strange things with TACAN - can you confirm the version of FlightGear you were flying with.

**Comment by dirteat** [comment]
yes, sorry, it is next (2020.4.0), close to latest snapshot (01/2023).

**Comment by vanosten** [comment]
I am on Windows NEXT flying the latest git version of 1.12. I also experience the same problem. 

In the following picture the MP carrier is almost straight ahead on the right side of the HUD - but the heading indicator is showing another direction. Range is correct.

![fgfs-20231223201631](https://github.com/Zaretto/fg-aircraft/assets/245995/5781daeb-af5e-486b-9fec-0fb7b66d0723)

**Comment by vanosten** [comment]
Also: if I add a pure coordinate (e.g. 19.,70.9) in the route manager it will accept it, but I cannot activate the line - it will automatically jump to the next line. Airports etc. work.

**Comment by vanosten** [comment]
Both TACAN and route manager seem to work

**Comment by Zaretto** [comment]
Fixed in commit 48e25f29
