### ISSUE TITLE
F-15C: Seeing another F-15C, console reports some missing files

### ISSUE THREAD

**Issue by NikolaiVChr** [Zaretto/fg-aircraft#19]
Cannot find image file "Models/Effects/interior/0004.png"
Cannot find image file "Models/Effects/interior/0002.png"
Cannot find image file "Models/Effects/interior/0001.png"
Cannot find image file "Models/Effects/interior/0003.png"
Cannot find image file "Models/Effects/interior/0006.png"
Cannot find image file "Models/Effects/interior/0005.png"
Cannot find image file "Models/Effects/interior/reflection-ws/0004.png"
Cannot find image file "Models/Effects/interior/reflection-ws/0002.png"
Cannot find image file "Models/Effects/interior/reflection-ws/0001.png"
Cannot find image file "Models/Effects/interior/reflection-ws/0003.png"
Cannot find image file "Models/Effects/interior/reflection-ws/0006.png"
Cannot find image file "Models/Effects/interior/reflection-ws/0005.png"
Cannot find image file "Models/Effects/interior/reflection/0004.png"
Cannot find image file "Models/Effects/interior/reflection/0002.png"
Cannot find image file "Models/Effects/interior/reflection/0001.png"
Cannot find image file "Models/Effects/interior/reflection/0003.png"
Cannot find image file "Models/Effects/interior/reflection/0006.png"
Cannot find image file "Models/Effects/interior/reflection/0005.png"
Failed to load file: "Models/Effects/Fuel/fuel-dump.xml"

**Comment by Zaretto** [comment]
Caused by the way that FG resolves paths for the effect definition (.eff). All of the interior effects probably won't matter as 99% of the time it isn't possible to site inside an MP aircraft. I might actually disable the effect by default to save a bit of shader time for MP.

The fuel dump is slightly more important and I'll get this fixed.

**Comment by Zaretto** [comment]
Should now be resolved.
