### ISSUE TITLE
F-14b steer cmd buttons not working in the display panel

### ISSUE THREAD

**Issue by Kuvaaja222** [Zaretto/fg-aircraft#190]
I dont know if its a bug or a normal thing. 
I downloaded recently the f-14 from github because i heard that the launcher one is old. But when i open the newly downloaded plane it was almost same to the "old" one. Because the exsact buttons didnt work(like the steer cmd mode selector buttons in the display panel).
Im not sure that im 100% correct that the "old" version is even old but i would just like to know if im using the best version of the f14 that i can.
![image](https://github.com/Zaretto/fg-aircraft/assets/100865849/be635564-e974-4469-ad96-517dcc7c41cf)

 
my launcher version is 2020.3

**Comment by Megaf** [comment]
Hi there! How are you?
Could you please test with the branch `release/1.12`? That's the currently developed branch and where the newest F-14 and F-15 are! ;)

https://github.com/Zaretto/fg-aircraft/tree/release/1.12

**Comment by Kuvaaja222** [comment]
Yeah someone just sent me the wrong link, but thanks.
