### ISSUE TITLE
When seeing an F15 in MP, it appears as if only 1 engine is working

### ISSUE THREAD

**Issue by NikolaiVChr** [Zaretto/fg-aircraft#20]
Very often when seeing an F15C in MP, it appears as if only 1 engine is working, even though both is running.

**Comment by Zaretto** [comment]
Thanks for the report. 

Can you just clarify what isn't working: Augmentation, Nozzles position, Gauges, Smoke

**Comment by NikolaiVChr** [comment]
When somebody else is flying the f15 within range of me. I switch to model view to look at him. The one engine seems like its out, no augmentation effect, no engine light.

The pilot however always tell that both his engines are working.

If the nozzle is animated correct I did not notice.

I have seen it quite often.

F15 version 1.3 in FG 2016.1.1

**Comment by Zaretto** [comment]
Fixed in commit 50f7a641e03e8d3f4059c50d9350fa1979924975
