### ISSUE TITLE
F-15C A/P true heading lock seems to work as a wing leveler

### ISSUE THREAD

**Issue by NikolaiVChr** [Zaretto/fg-aircraft#21]
When flying the F-15C and putting on A/P true heading lock, all it seems to do is level the wings.

**Comment by Zaretto** [comment]
In the cockpit we only have ATT Hold and ALT Hold; so I'm assuming you mean from the dialog.

**Comment by NikolaiVChr** [comment]
That's correct.

**Comment by Zaretto** [comment]
Thanks for clarifying. 

Also related to #15 - there is more work to do on the autopilot and nav and it's in-progress

**Comment by Zaretto** [comment]
Josh implemented a new autopilot that works as per the aircraft in terms of CSS and the available locks.
