### ISSUE TITLE
F-15C: When firing cannon the ammo goes to zero

### ISSUE THREAD

**Issue by NikolaiVChr** [Zaretto/fg-aircraft#22]
I load up the f15c.

Reproduce:
Put masterarm on.
Switch to cannon using 'm' key.
Pull trigger.
Observe the ammo goes to zero, and no shoots fired.

Workaround:
Go in fuel and stores
Click reload cannon.
Now it will fire.

**Comment by Zaretto** [comment]
Will be fixed in the next release.

**Comment by Zaretto** [comment]
fixed by bb5486cd2df7f112db776d56188d7d815b657ab7
