### ISSUE TITLE
F-15C startup errors in console.

### ISSUE THREAD

**Issue by NikolaiVChr** [Zaretto/fg-aircraft#23]
When I start up F-15C version 1.3, I get these:

In file C:/Users/Nikolai/Documents/FlightGear/Aircraft/FG36/F-15/Systems/f-15-electrics.xml: line 33
      Property systems/electrics/emerg-generator-status is already defined.

FGPropertyManager::GetNode() No node found for gear/gear-dmd-norm
FGPropertyManager::GetNode() No node found for gear/gear-dmd-norm
FGPropertyManager::GetNode() No node found for gear/gear-dmd-norm
FGPropertyManager::GetNode() No node found for gear/gear-dmd-norm
FGPropertyManager::GetNode() No node found for /consumables/fuel/tank[5]/selected
FGPropertyManager::GetNode() No node found for /consumables/fuel/tank[6]/selected
FGPropertyManager::GetNode() No node found for propulsion/engine[0]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[0]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[0]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[0]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[0]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[0]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[0]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[1]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[1]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[1]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[1]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[1]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[1]/augmentation-alight
FGPropertyManager::GetNode() No node found for propulsion/engine[1]/augmentation-alight
Failed to tie property fcs/elevator-control to object methods
Failed to tie property fcs/aileron-control to object methods
Failed to tie property fcs/left-aileron-normalization to object methods
Failed to tie property fcs/aileron-control to object methods
Failed to tie property fcs/steer-pos-deg to object methods

**Comment by Zaretto** [comment]
This is normal; it's due to dependencies between the jsbsim systems ; I've attempted to resolve this by defining these properties within the -set file; but that simply created a duplicate set.

**Comment by Zaretto** [comment]
I've mostly fixed all of these now.
