### ISSUE TITLE
F15c: The cannon pitch makes it hard to aim.

### ISSUE THREAD

**Issue by NikolaiVChr** [Zaretto/fg-aircraft#25]
The cannon pitch at 1.7 deg makes it hard to aim at another fighter.

Reducing it to 0.0 makes it much easier.

**Comment by Zaretto** [comment]
I think the M61 is actually in a completely wrong place. I will investigate this

**Comment by Zaretto** [comment]
I've merged your changes 7af1f1f9e9374ab07e74167b39765c55ef40c096
