### ISSUE TITLE
Define fuel receptacle points

### ISSUE THREAD

**Issue by onox** [Zaretto/fg-aircraft#27]
I have a version of the 707-TT that has a moveable refueling boom. If an aircraft defines a fuel receptacle in its model XML file, the tanker's refueling boom can snap to it and automatically track it. Support for the drogues will be added in the future.

For this to work, aircraft need to define some properties in their model XML file. These properties are automatically inserted in the property tree when the model XML file is loaded when an aircraft is visible in the pilot list. These properties are static and not transmitted in MP packets, thus the user with the tanker needs to have updated aircraft that contains these static properties. The properties are harmless for any user that doesn't fly a tanker that supports them.

I have calculated the coordinates for the F-15 and F-14.

In `Models/f15c.xml` below `</path>`, the following can be added:

```xml
<multiplay>
    <refuel>
        <offset-x-m type="double">-0.3457</offset-x-m>
        <offset-y-m type="double">-1.6912</offset-y-m>
        <offset-z-m type="double">0.7946</offset-z-m>
    </refuel>
</multiplay>
```

And in `Models/f-14b.xml`:

```xml
<multiplay>
    <refuel>
        <offset-x-m type="double">-7.1969</offset-x-m>
        <offset-y-m type="double">1.0409</offset-y-m>
        <offset-z-m type="double">0.0387</offset-z-m>
    </refuel>
</multiplay>
```

**Comment by Zaretto** [comment]
This looks useful; I'll add it into the next release.
