### ISSUE TITLE
F15: Button to enable MP chat hit msgs

### ISSUE THREAD

**Issue by NikolaiVChr** [Zaretto/fg-aircraft#31]
Feature request:

A button like the F14 has, to enable missile hit messages over MP chat.

**Comment by NikolaiVChr** [comment]
I have written an anti-cheat system, sadly we need it due to some of the kids in our group. :|

But I would like that its not active all the time, sometimes one would like to take a flight, and not be bothered about a message because one refueled in air etc.

With such a button, it would tie nicely in such that the anti-cheat system is only active when MP hit chat msgs is enabled.

**Comment by Zaretto** [comment]
The same button that is in the F-14 is already commented out inside dialogs/external-loads.xml please just add re-enable it as you wish.

Regarding anti cheat; it would be a reasonably good idea to transmit the weight in all aircraft (there is a proposed property for it). That way the anti-cheat system can check other MP aircraft to make sure this keeps decreasing by a reasonable amount (say a minimum of 20lbs per minute). If weight stays the same or increases there must be foul play afoot.

**Comment by NikolaiVChr** [comment]
Thank you, have re-enabled that button. :)

Yes, I remember you suggested that before. But then also have to transmit WoW to make sure that the foul play was done while in the air and not on the runway, where it would be okay. And would have to do the check fairly often, to make sure people don't rearm on the runway, take off, and then the check is being done and concludes foul play, while really it was done on the runway. It is a good idea though, will think a bit more about it.

**Comment by Zaretto** [comment]
We are constantly scanning the AI tree for the radar, so to add an extra check on weight would be easy. Just remember the last value and last speed. If weight doesn't decrease whilst speed is greater than say 80 something is wrong. That's how I'd do it anyway; because it's way harder to remove as any aircraft not having valid weight figures must be cheating.

However on the last mission I did take off and forgot to fuel so I refuelled in air from the tanker.

**Comment by NikolaiVChr** [comment]
Yeah, you're right it would be more difficult to remove. Pinto is/was however working on md5 hash checks on certain aircraft files, so we can see if an aircraft has been modified, not sure how far he got with that.

Dammit, refueling in air is something I did not account for in anti-cheat code. Not sure how to build that in.

**Comment by Zaretto** [comment]
/systems/refuel/contact

**Comment by NikolaiVChr** [comment]
Thank you!

**Comment by NikolaiVChr** [comment]
Closing this issue since its solved. :)
