### ISSUE TITLE
Create A/G capacity with the F15C

### ISSUE THREAD

**Issue by Raider11** [Zaretto/fg-aircraft#36]
Allow A/G weapons to be manually targeted and released from the center pylon, and the tank pylons on the wings, IAW http://www.avialogs.com/viewer/avialogs-documentviewer.php?id=3706 (beginning page 90, Section 10).

Allow the MCD to be used to target weapons (as opposed to the VSD) as is in later block F15s.

**Comment by Zaretto** [comment]
We now have partial A/G capability with the MK-84 JMTD that can lock onto targets that are present in MP. 

No support for dumb weapons as yet; this is still pending.

**Comment by Zaretto** [comment]
Closing this as @NikolaiVChr has implemented this.
