### ISSUE TITLE
f-14a: Cannot find objects for animation

### ISSUE THREAD

**Issue by onox** [Zaretto/fg-aircraft#5]
I get the following when loading the f-14a:

```
Could not find at least one of the following objects for animation: 'AfterburnerL', 'TurbineL', 'AfterburnerL.001'
Could not find at least one of the following objects for animation: 'AfterburnerR', 'TurbineR', 'AfterburnerR.001'
Could not find at least one of the following objects for animation: 'ReheatL'
Could not find at least one of the following objects for animation: 'ReheatR'
Could not find at least one of the following objects for animation: 'fx'
```

Afterburners seem to be visible though.

**Comment by Zaretto** [comment]
I'm still working on the afterburners in general; and this should be resolved shortly.

I'm trying to get them to look like this: 1:01 in this https://www.youtube.com/watch?v=lQOIw-6aXS4&list=PLrWcNdpaLs_MkJ_4otXktem0IxORu-MYg&index=8

**Comment by Zaretto** [comment]
This has now been fixed; the soon to be pushed F-14 has revised (again) afterburners.
