### ISSUE TITLE
F-14B: LSO lights at nose wheel are also visible when retracted

### ISSUE THREAD

**Issue by vanosten** [Zaretto/fg-aircraft#55]
![lso_lights](https://user-images.githubusercontent.com/245995/43999543-783d64c2-9e0e-11e8-9e7b-a13bd2966ef8.png)
The three LSO-lights should IMHO only be visible when the nose wheel is out.

**Comment by Zaretto** [comment]
Thanks for the report.

The problem is that these should be attached correctly to the nose gear and rotate with it. This is what I'll fix.

**Comment by Zaretto** [comment]
Fixed V1.8; 2018-09-08
