### ISSUE TITLE
F-14B: Instability issues at low airspeed with gears and flaps down

### ISSUE THREAD

**Issue by vanosten** [Zaretto/fg-aircraft#56]
Suggest merging in the Case1-dev branch, as it IMHO improves the stability significantly.

**Comment by Zaretto** [comment]
Thanks for the feedback. 

My original plan was to release this at the same time as 2018.3 (due to the additional dependencies in FGData that fix carrier replays); however I may do a partial release prior to this.

**Comment by Zaretto** [comment]
Merged revised low speed aero V1.8
