### ISSUE TITLE
f-14 elevator trim (center of gravity) issue??

### ISSUE THREAD

**Issue by awnek** [Zaretto/fg-aircraft#64]
Hi guys
Thanks for your effort on F-14. I love this AC very much. :)
With latest update I have some issues with elevator trim (centrer of gravity??) With elevators on neutral aircraft is very heavy on the nose. To trim it, elevators have to go up to around 10 deg up. This trimming makes air plane very sensitive on the stick above 400kts when I'm pulling higher aoa (around 12 units and up). 
I have some issues with radar as well (not locking other AC) but since nobody else is reporting it I assume that it is my "local" problem.
Once more thanks for your job and regards
Adam

**Comment by Zaretto** [comment]
This has now been fixed - the problem was caused by an incorrect pitching moment for flaps=0 due to badly formed XML
