### ISSUE TITLE
Problems with the AWG-9 and AIM-54

### ISSUE THREAD

**Issue by SerafeimLiakos** [Zaretto/fg-aircraft#88]
I've noticed some problems with the AWG-9 and AIM-54 Phoenix in the F-14. It appears that this kind of trouble occurs both on AI and MP aircraft, and generally everything detectable in FG.

1. The AWG-9 radar has false indications of range on the RIO TID screen. For example when the radar range is set to 200 miles the target icon appears when the target is at 100 miles and appears at the top of the screen, which indicates the target is 200 nm away.

2. AIM-54's launch range sometime the AIM-54 faces some serious problems with its launch range, which:  sometimes gets dramatically decreased from 80 miles to 22 miles and sometimes it just won't lock.
           
                  VooDoo3

**Comment by Zaretto** [comment]
Thanks for making a bug report; I've taken the liberty of editing your bug report for clarity.

I'll look into these when time permits.

**Comment by SerafeimLiakos-VooDoo3** [comment]
Richard, thank you very much. You really don't know how happy I felt when I
read this.So, with a few words, thank you.

                                                  VooDoo3

**Comment by SerafeimLiakos-VooDoo3** [comment]
Alright, hopefully Richard, I found out that there's no problem with the AIM-54.Seems that having edited the weapons files to create new loadouts etc. meesd up the thing, but now with the F-14 and F-15 having been re-installed, I can lock a target and shoot him with an AIM-54 at 80nm or closer, like I could before modifying the file.So yeah, that's one trouble gone, now, when you have time, you can look into the false range indications on the TID when in radar mode.Thank you.

                                                                                                                         VooDoo3
