### ISSUE TITLE
Can not control F-14 with mouse and joystick

### ISSUE THREAD

**Issue by Potomac** [Zaretto/fg-aircraft#92]
Hello,

I use flightgear 2019.1.1 on archlinux,

I notice that I can not control F-14 with mouse and joystick, the yoke moves but ailerons, trims don't move, 

F-15 has the same problem, the others planes (C172P, 777, airbus etc..) don't have problem with mouse and joysticks,

F-14 and F-15 are really compatible with flightgear 2019.1.1 ?

Version of F-14 I use : v1.8 2018-08-20

**Comment by Zaretto** [comment]
For 2019.1 you need to be using V1.9 or later.

Also you need to have the engines running on both the F-14 and F-15 before the flight control surfaces will move.

F-14 and F-15 can be obtained from https://github.com/Zaretto/fg-aircraft/releases - and I'd recommend either nightly of 2019.2 or 2018.3 - 2019.1 isn't the best interim release we've made

**Comment by Zaretto** [comment]
Closing issue as retested and working correctly with 2020.3 LTS
