### ISSUE TITLE
F-14b modification proposal

### ISSUE THREAD

**Issue by SP-AWN** [Zaretto/fg-aircraft#93]
Hi 
First of all I very much appreciate your work on F14b aircraft. Thank you very much for that. 
Lately I started to compare this model performance with real world data, and I have some comments and modification proposal. I will try to be short ;), and sorry for my bad English  

1) Sustained turn rate
Please see sustained turn rate chart below
![obraz](https://user-images.githubusercontent.com/59488976/71751688-a195e880-2e7c-11ea-9c3f-a1d93688ed16.png)
Original FDM model is below of sustained turn rate charts I present above. I presume it is due to lifting surface area which is correct regarding to wing surface, but it is not taking lifting body surface into account. According to this very interesting lecture full lifting surface area is around 1008 sq. ft. Please see video below
https://youtu.be/SsUCixAeZ0A?t=1001
Of course simple change wing area is not an answer, because lifting body surface has different lift and drag coefficients than wings.  
I have no information regarding lifting body coefficients so I tried to "fiddle" with additional area and coefficients in try and error manner. Eventually I came with such modification in f-14b.xml:

>         <axis name="LIFT">
            <function name="aero/force/LIFT">
                <description>LIFT Force</description>
				<sum>
					<product>
						<property>aero/qbar-psf</property>
						<property>metrics/Sw-sqft</property>
						<property>aero/coefficients/Cl</property>
						<property>aero/coefficients/Cmach</property>
						<property>aero/coefficients/ClSweepFactor</property>
					</product>
					<product>
						<property>aero/qbar-psf</property>
						<value>190</value>
						<sum>
							<property>aero/coefficients/ClBAS</property>
							<property>aero/coefficients/DClDS1</property>
							<property>aero/coefficients/DClDS2</property>
							<property>aero/coefficients/ClUC</property>
							<property>aero/coefficients/ClDasym</property>
						</sum>
						<property>aero/coefficients/Cmach</property>
					</product>
				</sum>
            </function>
        </axis>
        <axis name="DRAG">
            <function name="aero/force/DRAG">
                <description>DRAG Force</description>
				<sum>
					<product>
						<property>aero/qbar-psf</property>
						<property>metrics/Sw-sqft</property>
						<property>aero/coefficients/Cd</property>
						<property>aero/coefficients/ClSweepFactor</property>
					</product>
					<product>
						<property>aero/qbar-psf</property>
						<value>190</value>
						<sum>
							<property>aero/coefficients/DCdDS1</property>
							<property>aero/coefficients/DCdDS2</property>
							<property>aero/coefficients/CdUC</property>
							<property>aero/coefficients/CdDasym</property>
							<property>aero/coefficients/CdDBRK</property>
							<property>aero/coefficients/CdTNK</property>
						</sum>
					</product>
				</sum>
            </function>
        </axis>
As you can see I added 190sq. ft of additional lifting surface with selection of already existing coefficients, excluding slats and flaps
This gave me quite good results up to some point. Please see chart below: It shows sustained turn g-load from test flight and from chart showed above
![obraz](https://user-images.githubusercontent.com/59488976/71752562-cdff3400-2e7f-11ea-90ab-2f9b466882c1.png)

As you can see numbers are similar up to 400-450KIAS Above that it goes "bananas" ;) It certainly need some adjustments above that area.
I have some software development experience, but I'm quite fresh to jsbsim, so these simple adjustment it is my limitations there ;) 

2) AOA indicator:
F-14 AOA indicator works in units not in degrees. My internet search shows that unit/degrees conversion equations are as follows:
AOA deg = (A0A units -3.715)/1.089
AOA units = (AOA deg + 3.715) * 1.089
That why I changed aoa-gauage.xml according to this equations :

> 	<animation>
		<type>textranslate</type>
		<object-name>tape</object-name>
        <property>orientation/alpha-indicated-deg</property>
        <interpolation>
				<entry><ind>-3.411</ind><dep>0</dep></entry> 
				<entry><ind>24.14</ind><dep>0.5</dep></entry> 
		</interpolation>
		<axis>
			<x>0</x>
			<y>-1</y>
		</axis>
	</animation>
To correct approach speed indicator I changed f-14-common.xml:

> <aoa-indexer>
                        
                        

                        <slow-deg-start>10.82</slow-deg-start>
                        <optimum-deg-start>9.44</optimum-deg-start>
                        <optimum-deg-end>11.28</optimum-deg-end>
                        <fast-deg-end>9.9</fast-deg-end>

                        <target-deg>15</target-deg>
                        

                    </aoa-indexer>
With this modifications we get proper approach aoa. eg.: total weight 51000lbs speed 130kt aoa 15 units. Which confirms also my "additional" lifting surface estimation, at low and medium speeds.
Please feel free to comment and utilize these results if you find them useful.
Regards
Adam :)

**Comment by Zaretto** [comment]
Introduction
------------
I've already spent a good amount of time tuning the F-14 for the approach configuration; and it is my belief that at 50000lbs onspeed is about 130kts. ref: 00254087744f35b9c93f1cccf7c6343d18277f0e

Sustained Turn rate:
------------
The coefficients already take into consideration the entire aircraft - see the original data source here: http://zaretto.com/sites/zaretto.com/files/F-14-data/ADA101648.pdf page 51.

However the figures for flaps, slats, airbrakes, gear, stores, wing sweep, mach are not from the original data source - all of these are based on my own calculations and may be inaccurate especially mach and wingsweep.

![image](https://user-images.githubusercontent.com/2045654/71763921-3252df80-2ee2-11ea-807b-55b766d95ed0.png)

Take into consideration when readings these charts.
- There may be some discrepancies also on the measured G
- Almost certainly there is a technique to get to the figures in the chart; it won't be a case of simply going stage 5 AB and pulling back hard on the stick.
- There is likely to be variations across different airframes; so these figures are probably accurate to within 3% to 15% (my estimation)
- as indicated below it is important to match all of these when flight testing.

![image](https://user-images.githubusercontent.com/2045654/71765685-178b6580-2ef8-11ea-9249-39bb5a85e16d.png)

Aircraft tuning
------------------
The way to tune the aircraft is to start at the reference data point; which for this F-14B is MN 0.6 "clean" (no slat or flap deflection), wing sweep 22 deg.

It is safe to assume that Lift & Drag are correct at MN 0.6, clean, sweep 22 deg. 

The correct method to find out what is incorrect is firstly to remove mach and wingsweep from the coefficients (as these could be the problem). 

It is also better to test against a "clean" (no stores) configuration 

Then ensure 
- that the atmosphere is correct; standard day 1013 
- the aircraft is clean (no flaps, slats, gear, speedbrake)
- the aircraft has the correct mass
- engine power is set appropriately.
- probably use fuel freeze to aid with testing.


Alpha Units
-------------
This is already calculated into property indicated-alpha-deg; see https://github.com/Zaretto/fg-aircraft/blob/master/aircraft/f-14b/f-14a.xml#L1570[1]

![image](https://user-images.githubusercontent.com/2045654/71763776-1bab8900-2ee0-11ea-9bf9-8ee55d23f454.png)

I'm reasonably happy that the approach numbers are a close match to aircraft performance; it's not easy to land on a carrier but it is also my view that this is correct. 

Test conditions: approach configuration, full flaps, hook, gear, case 1 recovery, 50000lbs onspeed is about 130kts. see also commit: 0025408

-----------------
[1] NASA TM-81833, page 56, Figure 17

**Comment by SP-AWN** [comment]
Hi, 
Thanks for reply.
Of course I was using similar AC configuration to test performance as shown in chart. Standard day. The same weight and stores. My approach is not to pull back as hard as possible, but to keep load sufficient to stay on desired speed. I will try to investigate more in my free time. 
Regarding true aoa and indicated aoa I think we are talking different stuff there. Units which are shown on aoa gauge are not true or indicated aoa, and they are different for eg.  F-15 and F-14. Please see video attached. It is form DFCS. I read about that also in some other document while ago, so I can't bring it there.
https://www.youtube.com/watch?v=4yZIG47h-4E
Regards and thanks again
Adam

**Comment by SP-AWN** [comment]
OK finally I have found it.
https://apps.dtic.mil/dtic/tr/fulltext/u2/a243109.pdf
In this document on page 28 you can find table which shows correspondence between aoa units and degrees for F-14. 
Units are displayed on pilots indicator. So if plot approaches with 15 units on  aoa indicator it is slightly above 10 deg. So its looks pretty the same as  I proposed in first post.
![obraz](https://user-images.githubusercontent.com/59488976/71767821-b623c080-2f10-11ea-907d-a5e4598a6c6f.png)

Regards
Adam

**Comment by Zaretto** [comment]
It is important to use standard day as defined in the document associated with the chart - using basic weather and ensuring that both the pressure and temperature are correct for the chosen flight test altitudes.

The performance chart you've provided is useful although it will not be easy to figure out what needs to be fixed because it has stores and that increases the number of possible things that could be wrong.

**Comment by Zaretto** [comment]
The DCS folks to seem to struggle with what AoA units are; however I figured this out back in 2014. 

The only thing that has been confusing is that the two sources of information that I have found contradict each other.

Thanks for the data that you've provided; unfortunately we now have 3 definitions of the conversion between true AoA (degrees) and indicated AoA (units); as below.

![image](https://user-images.githubusercontent.com/2045654/71769190-1b31e300-2f1e-11ea-9ce1-b3b472b9b96b.png)

**Comment by SP-AWN** [comment]
Yes. I'm not sure which aoa degrees are input for units equation. 
From my real world aviation experience (gliders and small airplanes - non of them have aoa measuring device installed). 
Most of aircraft instruments like speed indicator, variometer, altitude  indicator or compass have something like correction charts which indicates deviation between measured values and true values. It is due to instrument measurement "errors". In gliders and small airplanes these chats are placed somewhere inside cockpit. Most probably it is the same with aoa measuring device, it measures values with some error which is described by chat you presented. (Although always such charts are individual to particular piece of instrument.) 
My guess. Since aoa gauge uses this equipment as data source than indicated-aoa should be used as input to units calculation. But it is only guess
Regards
Adam

**Comment by Zaretto** [comment]
The work in the  2020-flaps-tuning branch in commits 26427e28 71cb5fdb 15430cfe 5293ccc9 de1c39a6 67d95553 means that we are now using windtunnel data for flaps, speedbrake, landing gear, spoilers

As such it is my view that this issue is now resolved.
